### ISSUE TITLE
Homebar

### ISSUE THREAD

**Issue by mody216** [CPDigitalDarkroom/Barmoji#1]
First thing i would like to thank you for that amazing tweak

second thing i want to mention that sometimes when I try to slide between emojis i accidentally switch apps can you fix this by moving the emoji up little bit?

**Comment by jcarlosperez** [comment]
I'll be adding an adjustment slider in a settings pane so users can offset it a bit. For me, the OCD of it not being aligned with the other two buttons would irk me haha.

**Comment by NSExceptional** [comment]
I think this could be mitigated by raising the scroll view itself up almost to the bottom of the spacebar, while lowering the emojis themselves so that they look aligned with the buttons. Then you don't have to reach so far down to scroll.

**Comment by CPDigitalDarkroom** [comment]
Thanks, @NSExceptional for that suggestion. Late fix but finally got this done.

**Comment by NSExceptional** [comment]
Did you end up doing my suggestion? I totally forgot about my idea haha

**Comment by CPDigitalDarkroom** [comment]
I did. Adjusted the collection view and inset the top margin to keep the aligned look. Works much better for daily use with this small change.
