### ISSUE TITLE
Barmoji only works properly on 1.3.1

### ISSUE THREAD

**Issue by mainhathao** [CPDigitalDarkroom/Barmoji#11]
Versions later than 1.3.1 only works sometimes. Have to trigger keyboard again to activate emojis in the bottom bar/predictive bar. 1.3.1 is the most stable version and works on A12 but the preference bundle doesn't work.

**Comment by CPDigitalDarkroom** [comment]
Are there certain apps you can reproduce the issue consistently?

**Comment by itzedy** [comment]
Snapchat, Facebook, Messenger, Youtube. When you don’t have the app running in background and you open it, click search and they won’t appear, then click search again and they will be there.

**Comment by mainhathao** [comment]
True, but isn’t that annoying though? To have to trigger the keyboard again sometimes...

Andrew

**Comment by itzedy** [comment]
Yeah it is, I was just saying how to reproduce it, but i mean pretty much anytime you bring up the keyboard you have to do it again a 2nd time

**Comment by mainhathao** [comment]
True, 1.3.1 is way more stable.

Andrew

**Comment by CPDigitalDarkroom** [comment]
I see what my changes are and through debugging I have confirmed the implementation I changed to in the 1.3.2 build to support Selectmoji causes the bug. I have reverted back to my previous implementation and added support for setting custom emojis for the bar directly in preferences. 

Version 1.5 should be live soon, let me know if this fixes the issue for y'all.

**Comment by itzedy** [comment]
Works great! Thanks.

**Comment by mainhathao** [comment]
It works like a charm now! Thank you so much!

Andrew
