### ISSUE TITLE
Various compile errors

### ISSUE THREAD

**Issue by NSExceptional** [CPDigitalDarkroom/Barmoji#13]
I'm compiling Barmoji from source for the first time, and it looks like not everything was properly committed to source control. Here are some examples:

```
==> Compiling BarmojiRootListController.mm (arm64)…
BarmojiRootListController.mm:64:16: error: instance method '-setValues:titles:' not found (return type defaults to 'id')
      [-Werror,-Wobjc-method-access]
    [specifier setValues:@[@(1), @(2)] titles:@[@"Recent", @"Custom"]];
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/theos/vendor/include/Preferences/PSSpecifier.h:119:12: note: receiver is instance of class declared here
@interface PSSpecifier : NSObject {
```

```
BarmojiRootListController.mm:185:23: error: no matching function for call to 'MGCopyAnswer'
  build = (NSString *)MGCopyAnswer(kMGBuildVersion);
                      ^~~~~~~~~~~~
/opt/theos/vendor/include/MobileGestalt/MobileGestalt.h:31:15: note: candidate function not viable: requires 2 arguments, but 1 was provided
    CFTypeRef MGCopyAnswer(CFStringRef question, CFDictionaryRef options);
```

I'm guessing the associated files in `vendor` are just old. If you've updated them by hand maybe a PR is in order?

**Comment by CPDigitalDarkroom** [comment]
The first one has to do with PSSpecifier interfaces. I've had to add a lot myself for things I've needed. You'll have to interface them manually. I may be able to upload my include folder sometime. 

The second I'm not sure, I've only used it with one argument and even examples of it show it with one. http://iphonedevwiki.net/index.php/LibMobileGestalt.dylib

**Comment by NSExceptional** [comment]
If you can just ZIP them up I'd be happy to make the PR on your behalf! Working on a PR for Barmoji and I need all this to get it to compile haha.

I did just edit my post almost as you commented, you may need to re-read the last part. I came to the conclusion that it's just non-standard headers because the standard ones are outdated and someone needs to make a PR

**Comment by NSExceptional** [comment]
Just got it to compile by hand, saw this as well:

```
Makefile:17: FW_STAGING_DIR is deprecated. Please migrate to THEOS_STAGING_DIR.
```

**Comment by CPDigitalDarkroom** [comment]
[Preferences.zip](https://github.com/CPDigitalDarkroom/Barmoji/files/3154465/Preferences.zip)

**Comment by NSExceptional** [comment]
Can you add your `MobileGestalt.h` as well? Thanks!

**Comment by CPDigitalDarkroom** [comment]
I'm using the one from the theos repo no changes.

**Comment by NSExceptional** [comment]
The one in the repo uses a version of `MGCopyAnswer` which [takes two arguments](https://github.com/theos/headers/blob/master/MobileGestalt/MobileGestalt.h#L31), are you sure it's unmodified? You're using the variant which takes one argument

**Comment by CPDigitalDarkroom** [comment]
Weird, I don't remember ever modifying that file. Here's what I got. I haven't pulled from the theos headers in a while due to mine being so modified in some places.


[MobileGestalt.h.zip](https://github.com/CPDigitalDarkroom/Barmoji/files/3154500/MobileGestalt.h.zip)
