### ISSUE TITLE
Barmoji not working at all.

### ISSUE THREAD

**Issue by gilshahar7** [CPDigitalDarkroom/Barmoji#2]
I'm on iPhone X , iOS 11.1.2, tried with Electra beta 6 and beta 6-3.
using stock keyboard and 3rd party keyboard, in multiple apps (stock and appstore apps).
it just show a normal bar below the keyboard. no change with the tweak.
i placed both files at /bootsrap/Library/SBInject and gave both of them "0777" access permissions.
i tried rebooting and respringing (using the anemone app).

**Comment by jescowalker** [comment]
i have the same issues as him . iphone x 11.1.2 using electra beta 6-3. loaded all the files correctly with 0777 as permission and didnt work at all. what could be the issue ?

**Comment by bao3** [comment]
Me too , iOS 11.1.2 iphone X . I gave the two files privilege 0777 , respring && uicache  . I'm using English IME

**Comment by Qteezy2015** [comment]
I’m having the same issue on iPhone X 11.1.2 just doesn’t show up at all and changed all permissions to have full acces

**Comment by bao3** [comment]
Guys, I just know what happened. You should use the original IME to input the emoji , then this tweak "barmoji" would remember the emoji and show it on the bar .

**Comment by Qteezy2015** [comment]
I don’t understand can you explain a little further please?

**Comment by ccsasuke** [comment]
Can confirm. It only shows the most frequently used emojis, typed using the stock Emoji keyboard. It will not show anything before you type in some emojis (not including 3rd-party keyboards).

**Comment by Pajerus** [comment]
Same exactly issue. Can someone comment a tutorial how to fix it and explain it?

**Comment by CPDigitalDarkroom** [comment]
Use the stock emoji keyboard for there to be recents in the system for it to show. In the latest update you can also set custom emojis so I consider this closed.
