### ISSUE TITLE
Hide Barmoji in predictive bar when suggestions appear

### ISSUE THREAD

**Issue by NSExceptional** [CPDigitalDarkroom/Barmoji#21]
When Barmoji replaces the predictive bar, it covers up suggestions like app passwords, phone numbers, addresses, etc, in iOS 12. Ideally there should be some way to detect when they appear and hide Barmoji until they disappear or are used.

At the very least, we could hide Barmoji when the user is in a secure entry text field and that would work for passwords.

**Comment by NSExceptional** [comment]
I have resolved this. I made it so that it hides the Barmoji view when:

- a text-replacement prediction is about to replace your typo, giving you a chance to cancel it, and
- when an autofill prediction appears (such as an address, phone number, or 2FA code)

I was going to submit a PR, but it looks like your `develop` branch with the latest changes has diverged from `master`. I can merge them for you if you'd like?

**Comment by jcarlosperez** [comment]
Merged, ready for the PR. Those are great improvements!
