### ISSUE TITLE
Barmoji shows for KeyboardTypes that don't support emojis

### ISSUE THREAD

**Issue by bnalls33** [CPDigitalDarkroom/Barmoji#22]
Some text fields have emojis disabled by setting custom keyboardTypes on the UiTextView.
Keyboards then hide their emoji buttons.
However, barmoji shows.

Some examples of keyboardtypes would be: UIKeyboardTypeASCIICapable (no UTF-8), emailAddress, etc

**Comment by jcarlosperez** [comment]
Although #25 resolves the issue for the predictive bar. A further code change is required to hide the bottom emoji bar for num pad keyboards.
