### ISSUE TITLE
Emojis in bar cut off in bottom bar

### ISSUE THREAD

**Issue by drippyer** [CPDigitalDarkroom/Barmoji#23]
iPhone X, iOS 13.2.2
Jailbroken with checkra1n 0.9.5 beta

Just wanted to get this up as an issue here in case you weren’t aware of it.

Image attached to best explain the issue:
![00ED5713-55BB-469F-9317-88680B9DEBA1](https://user-images.githubusercontent.com/6970779/68987417-877e4900-07ef-11ea-9b79-9f00e7da1940.jpeg)

**Comment by drippyer** [comment]
Let me know if there’s any other info that would be useful in getting this one solved or if you want me to test a .deb!

**Comment by CPDigitalDarkroom** [comment]
Fixed in the latest beta version. Public release soon.

**Comment by austinBurn** [comment]
When is the public release
